Update .travis.yml
update travis yml with shell script

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,11 +1,13 @@
 language: java
 script: mvn -Dtest=JunitTestSuite test
 
-#after_script:
-   #- |
-    #    if [ "$TRAVIS_TEST_RESULT" = "0" ]; then
-     #       -git reset --hard HEAD~1  # revert to the last commit
-      #  fi
+after_script:
+   rc=$? #last run command status
+   if [[$rc -ne 0]]; then
+       -git rever HEAD # revert to the last commit
+       echo '[*] Build Tests failed, reverting to the last commit'
+       exit $rc
+   fi
 
 #after_failure:
 # -git reset --hard HEAD~1
